name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: 
      - 'frontend-app/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: 'frontend-app/pnpm-lock.yaml'
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Install dependencies
      run: pnpm install
      working-directory: ./frontend-app
      
    - name: Build
      run: pnpm run build
      working-directory: ./frontend-app
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./frontend-app/dist

  deploy:
    # CONFIGURACIÓN EXPLÍCITA
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4